import { board, decision, edge, step, terminal, type Template } from './template'

export const FLOWCHART_TEMPLATES: Template[] = [
  {
    id: 'user-signup-flow',
    name: 'User signup flow',
    description: 'User account creation and authentication flow',
    type: 'flowchart',
    content: board(
      [
        terminal('s1', 405, 60, 'Start'),
        step('s2', 405, 260, 'Landing page'),
        decision('d1', 415, 420, 'Has account?'),
        step('s3', 725, 420, 'Log in'),
        step('s4', 85, 420, 'Sign-up form'),
        step('s5', 85, 600, 'Verify email'),
        decision('d2', 415, 760, 'Email valid?'),
        step('s6', 85, 940, 'Create workspace'),
        terminal('s7', 405, 1100, 'Dashboard'),
      ],
      [
        edge('s1', 's2'),
        edge('s2', 'd1'),
        edge('d1', 's3', 'Yes'),
        edge('d1', 's4', 'No'),
        edge('s3', 's7'),
        edge('s4', 's5'),
        edge('s5', 'd2'),
        edge('d2', 's4', 'No'),
        edge('d2', 's6', 'Yes'),
        edge('s6', 's7'),
      ]
    ),
  },
  {
    id: 'checkout-flow',
    name: 'E-commerce checkout',
    description: 'Shopping cart to order confirmation flow',
    type: 'flowchart',
    content: board(
      [
        terminal('s1', 405, 60, 'Cart'),
        decision('d1', 415, 200, 'Signed in?'),
        step('s2', 725, 200, 'Member path'),
        step('s3', 85, 200, 'Guest checkout'),
        step('s4', 405, 380, 'Shipping'),
        step('s5', 405, 540, 'Payment'),
        decision('d2', 415, 680, 'Payment ok?'),
        step('s6', 725, 680, 'Payment retry'),
        terminal('s7', 405, 860, 'Order confirmed'),
      ],
      [
        edge('s1', 'd1'),
        edge('d1', 's2', 'Yes'),
        edge('d1', 's3', 'No'),
        edge('s2', 's4'),
        edge('s3', 's4'),
        edge('s4', 's5'),
        edge('s5', 'd2'),
        edge('d2', 's7', 'Yes'),
        edge('d2', 's6', 'No'),
        edge('s6', 's5'),
      ]
    ),
  },
  {
    id: 'support-escalation',
    name: 'Support ticket escalation',
    description: 'Ticket triage to resolution flow',
    type: 'flowchart',
    content: board(
      [
        terminal('s1', 405, 60, 'New ticket'),
        step('s2', 405, 260, 'Triage'),
        decision('d1', 415, 420, 'Known issue?'),
        step('s3', 725, 420, 'Send KB article'),
        step('s4', 85, 420, 'Assign L1'),
        decision('d2', 415, 600, 'Resolved in 24h?'),
        step('s5', 85, 780, 'Escalate L2'),
        step('s6', 85, 940, 'Engineering review'),
        terminal('s7', 405, 1100, 'Resolved'),
      ],
      [
        edge('s1', 's2'),
        edge('s2', 'd1'),
        edge('d1', 's3', 'Yes'),
        edge('s3', 's7'),
        edge('d1', 's4', 'No'),
        edge('s4', 'd2'),
        edge('d2', 's7', 'Yes'),
        edge('d2', 's5', 'No'),
        edge('s5', 's6'),
        edge('s6', 's7'),
      ]
    ),
  },
  {
    id: 'hiring-pipeline',
    name: 'Hiring pipeline',
    description: 'Candidate evaluation to onboarding',
    type: 'flowchart',
    content: board(
      [
        terminal('s1', 405, 60, 'Application'),
        step('s2', 405, 260, 'CV screen'),
        decision('d1', 415, 420, 'Fit?'),
        terminal('s3', 725, 420, 'Reject email'),
        step('s4', 405, 600, 'Phone screen'),
        step('s5', 405, 760, 'Technical interview'),
        decision('d2', 415, 900, 'Offer?'),
        step('s6', 405, 1080, 'Offer sent'),
        decision('d3', 415, 1220, 'Accepted?'),
        terminal('s7', 85, 1220, 'Closed'),
        terminal('s8', 405, 1400, 'Onboarding'),
      ],
      [
        edge('s1', 's2'),
        edge('s2', 'd1'),
        edge('d1', 's3', 'No'),
        edge('d1', 's4', 'Yes'),
        edge('s4', 's5'),
        edge('s5', 'd2'),
        edge('d2', 's6', 'Yes'),
        edge('d2', 's7', 'No'),
        edge('s6', 'd3'),
        edge('d3', 's8', 'Yes'),
        edge('d3', 's7', 'No'),
      ]
    ),
  },
  {
    id: 'incident-response',
    name: 'Incident response',
    description: 'Alert detection through post-mortem',
    type: 'flowchart',
    content: board(
      [
        terminal('s1', 405, 60, 'Alert fires'),
        step('s2', 405, 260, 'Acknowledge'),
        decision('d1', 415, 420, 'Sev 1?'),
        step('s3', 725, 420, 'Page on-call lead'),
        step('s4', 725, 580, 'Status page update'),
        step('s5', 85, 420, 'Create ticket'),
        step('s6', 405, 600, 'Mitigate'),
        step('s7', 405, 760, 'Root cause analysis'),
        terminal('s8', 405, 920, 'Post-mortem'),
      ],
      [
        edge('s1', 's2'),
        edge('s2', 'd1'),
        edge('d1', 's3', 'Yes'),
        edge('s3', 's4'),
        edge('s4', 's6'),
        edge('d1', 's5', 'No'),
        edge('s5', 's6'),
        edge('s6', 's7'),
        edge('s7', 's8'),
      ]
    ),
  },
  {
    id: 'feature-release',
    name: 'Feature release checklist',
    description: 'Feature development through production announcement',
    type: 'flowchart',
    content: board(
      [
        terminal('s1', 405, 60, 'Feature complete'),
        step('s2', 405, 260, 'Code review'),
        decision('d1', 415, 420, 'Approved?'),
        step('s3', 85, 420, 'Address feedback'),
        step('s4', 405, 600, 'QA pass'),
        decision('d2', 415, 760, 'Bugs found?'),
        step('s5', 725, 760, 'Fix bugs'),
        step('s6', 405, 940, 'Deploy to staging'),
        step('s7', 405, 1100, 'Deploy to production'),
        terminal('s8', 405, 1260, 'Announce'),
      ],
      [
        edge('s1', 's2'),
        edge('s2', 'd1'),
        edge('d1', 's4', 'Yes'),
        edge('d1', 's3', 'No'),
        edge('s3', 's2'),
        edge('s4', 'd2'),
        edge('d2', 's6', 'No'),
        edge('d2', 's5', 'Yes'),
        edge('s5', 's4'),
        edge('s6', 's7'),
        edge('s7', 's8'),
      ]
    ),
  },
]
